### ISSUE TITLE
data objects should be created by the user, not an admin

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#34]
the user should be able to create data objects by herself. manager should just check all is fine.

**Comment by sergiocontrino** [comment]
@Swarnalathaa is this just a matter to allow the 'add new data object' for users? now only for managers?

**Comment by sergiocontrino** [comment]
do i understand correctly that the user can add objects for all studies in her organisation?

**Comment by Swarnalathaa** [comment]
@sergiocontrino as per my understanding currently we are showing the studies and data-objects based on the user organization but in future if study/data-objects are shown based on the associated users then in that case the question you have raised will be resolved. (this is my understanding)

**Comment by sergiocontrino** [comment]
discussed in dev call: this is fine.

Data objects can now be created by the user. 
She has access to all objects in her organisation.
This is the agreed behavior (@Gerd-ECRIN).

**Comment by sergiocontrino** [comment]
done

**Comment by sergiocontrino** [comment]
@Gerd-ECRIN tested
