### ISSUE TITLE
add data object

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#39]
- Display title -> title
- make the field mandatory
- move object class and object type 1 row above (immediately after display title)
- some of the 'select an option' are in the drop down (object/type/class ...) and not in the text field
- URL: has a text 'enter a parameter' either nothing or example url (https://www.example.org/mydata)
- mandatory fields to be marked

**Comment by Swarnalathaa** [comment]
Still pending to mark mandatory fields

**Comment by sergiocontrino** [comment]
fixed
