### ISSUE TITLE
mandatory fields

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#48]
- [x] define list of mandatory fields (per page?)  SC
- [x] check that FE implements the constraint  SK
- [x] verify the DB situation SC
- [x] implement a clear demarcation for mandatory fields (is the * enough? should we use another color for field name? change the bold settings, now applied to all fields?) SK

**Comment by sergiocontrino** [comment]
NB: at the moment, the repo manager enter just the study title and then let the submitter fill the rest. idem for DO. so we cannot enforce the constraint on the FE, (unless we can distinguish the role of user?). DB will stay as it is (also because sometime the field is missing from MDR).

**Comment by sergiocontrino** [comment]
rather minimal:
study: title, type, status, start year
DO: title, type  (enough? depending on type?)

**Comment by sergiocontrino** [comment]
if the fields in the previous comment are fine, we can just set default values for status, start year (studies) and type (DOs). could lead to wrong assignemets (but repo manager can check)

**Comment by Swarnalathaa** [comment]
I can make conditional checks for the validation fields based on the role so it won't be an issue to make constrains in the FE

**Comment by sergiocontrino** [comment]
thank you @Swarnalathaa , perfect. i assign back to you for the implementation, i.e. mandatory fields in FE as defined previously
study: title, type, status, start year
DO: title, type
taking into account that RM will input only title for both.

**Comment by sergiocontrino** [comment]
tested as admin. TODO: as normal user.

**Comment by sergiocontrino** [comment]
the check of mandatory fields works fine with the normal user as well.
all the issues of the previous comment are still valid though: @Swarnalathaa could you please fix them so we can close this one?

**Comment by sergiocontrino** [comment]
the moving of the focus on the missing fields is done.
for the rest regarding wording in the fields/dropdown/headers will list them in another issue (see also doc in #47 )
