### ISSUE TITLE
login page: ecrin mdr button goes to CRR instead

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#49]
should go to 
https://crmdr.org/

**Comment by Swarnalathaa** [comment]
Currently it is going to the browsing module and we have discussed that the name of the button has to be changed. I guess this linkage to the mdr can be removed. what do you think

**Comment by sergiocontrino** [comment]
thank you @Swarnalathaa . i would keep this link to the mdr, but yes, a new button for the browsing is needed.
the link to the mdr could possibly become just text when the browsing button is in place.

**Comment by Swarnalathaa** [comment]
issue fixed with new login screen
