### ISSUE TITLE
add study page: put default in units

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#50]
please set the default to 'years', so submitter has to use the drop down only if different.
remove 'select an option..'

**Comment by Gerd-ECRIN** [comment]
"select an option" still visible and default

**Comment by sergiocontrino** [comment]
fixed as suggested. if this is found convenient we could extend it to other fields.
@Swarnalathaa, is it easy to avoid setting the field (i.e. sending it to the BE) if the connected field (in this case min age/max age) is not filled?
