### ISSUE TITLE
"view-eye" on "browsing"-page leads into empty details page

### ISSUE THREAD

**Issue by Gerd-ECRIN** [ecrin-github/rms-portal#54]
In addition the "Edit"-button has to be removed.
![grafik](https://user-images.githubusercontent.com/124359774/235123516-40dc37f0-9ae1-4d12-be96-401e130bf1a6.png)

**Comment by Swarnalathaa** [comment]
@Gerd-ECRIN  We are still working on the browsing module and once it is done you will see the data being populated

**Comment by sergiocontrino** [comment]
thanks @Gerd-ECRIN , this works now, closing the ticket.
