### ISSUE TITLE
Date-Fields counting down one day on save/apply changes

### ISSUE THREAD

**Issue by Gerd-ECRIN** [ecrin-github/rms-portal#66]
All date fields (testet for DTP and DUP) are going down one day on every save/apply cahnges even when they are not changed.

**Comment by sergiocontrino** [comment]
hi @Gerd-ECRIN could you test this one?

**Comment by Gerd-ECRIN** [comment]
@Swarnalathaa bug still present in Edge

**Comment by Gerd-ECRIN** [comment]
Looks good to me now. Solved.
