### ISSUE TITLE
contact us page

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#75]
i think we could changhe a few minor things:

- [x] can we move the form to the left? or remove the division in 2 sections?
- [x] can we add a 'confirm email address' text field with the usual check that it is the same as the other one?
- [x] i think also ths page has issue with mobile scrolling (see title)
- [x] the back sign: i think we could add a second button with 'cancel' or 'back to login page' beside the send button

**Comment by sergiocontrino** [comment]
i would still add a button with  'cancel' or perhaps more consistently 'back' beside the send button.
the rest works fine (tested)

**Comment by Swarnalathaa** [comment]
@sergiocontrino added the button next to send

**Comment by sergiocontrino** [comment]
hi @Swarnalathaa , could you please update the colour of the button to usual orange rather than red? let's keep red only for delete/dangerous actions
if you prefer another colour (i don't remember the options in the library) please update all the other 'back' buttons.

**Comment by Swarnalathaa** [comment]
@sergiocontrino changed the button colour to usual orange
