### ISSUE TITLE
sticky header and more compact view?

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#76]
i think we use too much space in the layout.
should we have less padding (and maybe spacing)?

**Comment by sergiocontrino** [comment]
for the moment @Gerd-ECRIN does not feel this is needed. he suggestes to add 'location' (e.g. 'study details') to the sticky header.

**Comment by Gerd-ECRIN** [comment]
To be complete the sticky header (and the page header) should have 3 parts:
1. Where:  location e.g. Study Details, Edit Study Details
2. What: Title of Details or Lists
3. Action: Edit, Save, Apply, Cancel, Back Button

**Comment by Gerd-ECRIN** [comment]
For e.g. Edit Transfer details the page header is not correct and the sticky header only shows buttons.

**Comment by sergiocontrino** [comment]
@Swarnalathaa, please format the sticky header according to @Gerd-ECRIN recommendations above.
notes: 

- there is no sticky header yet for viewing DT and DU, for the list of studies and of DO
- the order and text should be consistent: where, then what
- for the details, you can omit the 'details' word, i.e. Study: title actions

**Comment by sergiocontrino** [comment]
from study details header:
edit: trying to change (add) 'brief description' - apply changes does not work
note : DO works fine

**Comment by sergiocontrino** [comment]
fixed
