### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Gerd-ECRIN** [ecrin-github/rms-portal#78]
* Clicking at the user name in the top right corner, the User Profile is shown.
- Within user profile when clicking on email brings back to dashboard. The email should not be clickable.
- Within user profile an empty avatar is shown. Question: Is this avatar transferred from Life Science Login system? If not, does the RMS need avatars?
- Within user profile when clicking on My Profile - Account settings and more a window with Personal Information opens in background but User Profile stays open. It should close automatically.

**Comment by sergiocontrino** [comment]
- [ ] remove hyperlink from email
- [ ] fix sticky userprofile when clicking on 'my profile'
- [ ] all the fields of personal information are not working, and some should be filled automatically and not changeable (username): should we get rid of all?

**Comment by Swarnalathaa** [comment]
@sergiocontrino full name and email are the only information i am getting from the user service. correct username and organization information are missing

**Comment by sergiocontrino** [comment]
thanks @Swarnalathaa , making a new issue and closing this one.
