### ISSUE TITLE
not possible to browse easily from DO to studies

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#82]
to improve:

- [x]  in the DO page, the parent study should be a normal field (not a disabled drop down) linking to the study page
- [x]  in the study page we should display the RMS-xxx id rather than the current (useless) id

**Comment by Swarnalathaa** [comment]
@sergiocontrino For point 2, Currently we are showing sdOid which is unique and formatted in the way with ':' in it. we don't anyother unique id to show in the display other than this.

**Comment by sergiocontrino** [comment]
thanks @Swarnalathaa , i meant the id in this table


![Screenshot 2023-08-08 100633](https://github.com/ecrin-github/rms-portal/assets/1004258/216f02a2-b9ad-4b03-ac6a-0b46d777ddd9)


the id is only internal and i don't think it is useful for now, also the url uses the RMS-xxx id.

**Comment by Swarnalathaa** [comment]
@sergiocontrino  got it. will make the changes.
change has to be done only to the study table?

**Comment by sergiocontrino** [comment]
i think we could do also the data objects, either with the long id, i.e. studyID::xx, or just the xx.
please refer also to  #83, i think we need to change the formats of our ids.
i would suggest to use the long id version for the do page and when we decide on the new format the code should be ready.

**Comment by sergiocontrino** [comment]
ps: we can think what to do for DT and DU, for the moment i would keep the current id (which is used for the url).

**Comment by Gerd-ECRIN** [comment]
Perfect!

**Comment by sergiocontrino** [comment]
fixed. we need to change id format, at least for DO. 
@Swarnalathaa , please make the id also a link to the DO/study

**Comment by sergiocontrino** [comment]
done. probably need to open in same window though, to check.
