### ISSUE TITLE
change of link to TSD

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#84]
tsd has changed the link to upload data to tsd:

we should use

**crr.tsd.usit.no**

instead of

**covid-19-repo.usit.uio.n**

@kouylekov-usit

**Comment by Swarnalathaa** [comment]
@sergiocontrino is the change in the link is for both uploading and downloading the data or just for upload?

**Comment by sergiocontrino** [comment]
i think for both, @kouylekov-usit can confirm, but he is on holiday now (i think until mid august). please change to both for now. we will test.

**Comment by Gerd-ECRIN** [comment]
upload doesn't work any more!

**Comment by sergiocontrino** [comment]
@kouylekov-usit can you help?

**Comment by Gerd-ECRIN** [comment]
Upload is working again.
