### ISSUE TITLE
navigation: from the navigation band, open pages in place

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/rms-portal#89]
in the left section navigation band, the pages are opened on a new tab: they should open in place.

**Comment by sergiocontrino** [comment]
![image](https://github.com/ecrin-github/rms-portal/assets/1004258/51599844-ae0a-450c-9bdc-bddde01c0d82)

**Comment by Swarnalathaa** [comment]
@sergiocontrino isn't the pages are opening in the same tab currently?
