### ISSUE TITLE
Browsing empty window

### ISSUE THREAD

**Issue by Gerd-ECRIN** [ecrin-github/rms-portal#92]
This morning
![grafik](https://github.com/ecrin-github/rms-portal/assets/124359774/d4ef7a47-52b7-4c66-936f-1ab59b36f753)

**Comment by Swarnalathaa** [comment]
@sergiocontrino @Gerd-ECRIN I have made the changes based on my understanding from today's tc but couldn't able to test completely. I have made a new release today and if @Gerd-ECRIN can check and see if the issue is fixed.

**Comment by Gerd-ECRIN** [comment]
Perfect, bug disappeared
